services:
  - type: web
    name: server-app
    env: node
    rootDir: server
    buildCommand: pnpm install
    startCommand: pnpm start:dev

  - type: static
    name: client-app
    rootDir: client
    buildCommand: pnpm install && pnpm run build
    staticPublishPath: dist

  - type: static
    name: providers-app
    rootDir: providers
    buildCommand: pnpm install && pnpm run build
    staticPublishPath: dist
